### ISSUE TITLE
Can't use `kn` argument for `LocalQlNear`?

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#213]
For some reason, I can't provide `kn` as a keyword argument to the constructor for `LocalQlNear`. I'm not sure if this is fixable or if it's a Cython problem. If I let it use the default (`kn=12`) or just provide it as an argument without the keyword, it seems to work fine.

```python
>>> freud.order.LocalQlNear(box=freud.box.Box.cube(3), rmax=1.3, l=6, kn=12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "freud/order.pyx", line 677, in freud.order.LocalQl.__cinit__
TypeError: __cinit__() got an unexpected keyword argument 'kn'
>>> freud.order.LocalQlNear(box=freud.box.Box.cube(3), rmax=1.3, l=6)
<freud.order.LocalQlNear object at 0x7f6410cb95e8>
>>> freud.order.LocalQlNear(freud.box.Box.cube(3), 1.3, 6, 12)
<freud.order.LocalQlNear object at 0x7f641df63288>
```

**Comment by bdice** [comment]
Fixed by #221.
