### ISSUE TITLE
Appveyor is failing

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#227]
Appveyor tests are currently failing - seems to be an issue beyond our control, but worth documenting for the moment. Seems related to the issues seen here, which were a "transient problem with outdated repodata on the mirror server": https://github.com/conda-forge/staged-recipes/issues/7498

I tried skipping the `conda update -q conda` call, which caused it to fail when installing other packages. I also tried using the previous image before the Feb. 11 image update (https://www.appveyor.com/updates/2019/02/11/) because I thought the issue might have been related to https://github.com/appveyor/ci/issues/2830. Unfortunately, that didn't fix the failing build.

https://ci.appveyor.com/project/glotzerlab/freud/builds/22409450

```
conda update -q conda
Solving environment: ...working... failed
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\Miniconda3-x64\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\subdir_data.py", line 95, in query
        self.load()
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "C:\Miniconda3-x64\lib\site-packages\conda\core\subdir_data.py", line 374, in _process_raw_repodata_str
        package_record = PackageRecord(**info)
      File "C:\Miniconda3-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Miniconda3-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 736, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Miniconda3-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 427, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "C:\Miniconda3-x64\lib\site-packages\conda\models\records.py", line 102, in box
        val = tuple(f for f in (ff.strip() for ff in val) if f)
    TypeError: 'NoneType' object is not iterable
`$ C:\Miniconda3-x64\Scripts\conda update -q conda`
  environment variables:
           APR_ICONV_PATH=C:\Program Files (x86)\Subversion\iconv
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Miniconda3-x64
             GIT_LFS_PATH=C:\Program Files\Git LFS
                 HOMEPATH=\Users\appveyor
                     PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;C:\Miniconda3-x64\Library\
                          bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site
                          \bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wb
                          em;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\7-Zip;C:\Program Files\Microsoft\Web Platform
                          Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git
                          LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft
                          SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\120\Tools\Binn\ManagementStudio\;C:\Tools\WebDriver;C:\Program
                          Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files
                          (x86)\Microsoft Visual Studio
                          12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft S
                          DKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:
                          \Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files
                          (x86)\CMake\bin;C:\go\bin;C:\Program
                          Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program
                          Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files
                          (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft
                          Visual Studio
                          14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program
                          Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL
                          Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\120\DTS\Binn\;C:\Program Files
                          (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program
                          Files\Mercurial\;C:\Program Files\dotnet\;C:\Tools\curl\bin;C:\Program
                          Files\Amazon\AWSCLI\;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 14
                          .0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Tools\vcpkg;C:\Pr
                          ogram Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program
                          Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\140\DTS\Binn\;C:\Program Files\erl9.2\bin;C:\Program Files
                          (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Git\cmd;C:\Program
                          Files\Git\usr\bin;C:\Program Files\Microsoft Service
                          Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service
                          Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program
                          Files\LLVM\bin;C:\Program Files
                          (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Roaming\npm;C:\Program
                          Files\PowerShell\6\;C:\ProgramData\chocolatey\bin;C:\Program Files (x8
                          6)\nodejs\;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\L
                          ocal\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program
                          Files\AppVeyor\BuildAgent\
             PSMODULEPATH=C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Users\appveyo
                          r\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShe
                          ll\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Progr
                          am Files (x86)\Microsoft SQL
                          Server\110\Tools\PowerShell\Modules;C:\Program Files (x86)\Microsoft
                          SQL Server\120\Tools\PowerShell\Modules;C:\Program
                          Files\AppVeyor\BuildAgent\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\130\Tools\PowerShell\Modules;C:\Program Files (x86)\AWS
                          Tools\PowerShell;C:\Program Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager;C:\Program
                          Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ServiceManagement;C:\Program Files
                          (x86)\Microsoft SDKs\Azure\PowerShell\Storage;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules;c:\Program
                          Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     active environment : None
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Miniconda3-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
Command exited with code 1
```

**Comment by bdice** [comment]
Seems resolved.
