### ISSUE TITLE
Buffer source array is read-only

### ISSUE THREAD

**Issue by yzjin** [glotzerlab/freud#244]
**Describe the bug**
Tried to use `pythia` and an error occurred in freud because the numpy array was read-only. It should be possible to compute analyses on read-only particle arrays.

**To Reproduce**
I tried to reproduce this bug with @bdice but we couldn't figure out what caused it. We know that switching the two lines here from `cdef float[:, ::1]` to `cdef const float[:, ::1]` fixes the problem.

https://github.com/glotzerlab/freud/blob/9f89a2211e18d192fdedd4121e9e65c62b92ce64/freud/environment.pyx#L478-L480

We expected this script to reproduce the problem but it doesn't show the error as expected:
```python
import freud
import numpy as np

points = np.eye(3)
points.flags.writeable = False
orientations = np.array([[1, 0, 0, 0]] * 3)
orientations.flags.writeable = False
box = freud.box.Box.cube(L=6)
nlist = freud.locality.NearestNeighbors(1, 1).compute(box, points, points).nlist
ld = freud.environment.LocalDescriptors(1, 4, 2)
ld.compute(box, 1, points, points, orientations, nlist=nlist)
print(ld.sph)
```

**Error output**
```
 Encountered error during program execution: 'buffer source array is read-only'
Execute with '--show-traceback' or '--debug' to get more information.
Traceback (most recent call last):
  File "./project.py", line 371, in <module>
    PathwayProject(config=source_project.config).main()
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 2737, in main
    _exit_or_raise()
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 2705, in main
    args.func(args)
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 2425, in _main_run
    run()
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/legacy.py", line 193, in wrapper
    return func(self, jobs=jobs, names=names, *args, **kwargs)
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 1608, in run
    np=np, timeout=timeout, progress=progress)
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 1408, in run_operations
    self._fork(operation, timeout)
  File "/nfs/turbo/bi-vislab/bdice/code/signac-flow/flow/project.py", line 1478, in _fork
    self._operation_functions[operation.name](operation.job)
  File "./project.py", line 342, in analyze_pathways
    train_inputs, train_outputs = makeDataset(mode, job.fn(dump_fname), frame_slice, frames)
  File "./project.py", line 121, in makeDataset
    descriptors = list(globalDescriptors(structure_fname, mode, frame_slice, limit=800)) #100 vs. 200, 300
  File "./project.py", line 114, in globalDescriptors
    yield computeParticleDescriptors(frame.box, frame.positions, mode, limit=limit)
  File "./project.py", line 82, in computeParticleDescriptors
    descriptors = pythia.spherical_harmonics.abs_neighbor_average(box, positions, **kwargs)
  File "/nfs/turbo/bi-vislab/bdice/code/pythia/pythia/spherical_harmonics.py", line 122, in abs_neighbor_average
    nlist))
  File "/nfs/turbo/bi-vislab/bdice/code/pythia/pythia/spherical_harmonics.py", line 88, in neighbor_average
    comp.compute(freud_box, nNeigh, positions, positions, orientations, nlist=nlist)
  File "freud/environment.pyx", line 480, in freud.environment.LocalDescriptors.compute
  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

**System configuration (please complete the following information):**
 - OS: Arch Linux 5.0.2
 - Version of Python: 3.6.7
 - Version of freud: 1.0

**Additional context**
The `const` feature was added to Cython to solve this exact problem: https://github.com/cython/cython/issues/1605

**Comment by bdice** [comment]
This script reproduces the problem. Note the change in `dtype`.
```python
import freud
import numpy as np

points = np.eye(3, dtype=np.float32)
# must use np.float32 so it's already in the right type
# or else freud's array conversion to float32 hides the problem

points.flags.writeable = False
orientations = np.array([[1, 0, 0, 0]] * 3)
orientations.flags.writeable = False
box = freud.box.Box.cube(L=6)
nlist = freud.locality.NearestNeighbors(1, 1).compute(box, points, points).nlist
ld = freud.environment.LocalDescriptors(1, 4, 2)
ld.compute(box, 1, points, points, orientations, nlist=nlist)
print(ld.sph)
```

**Comment by vyasr** [comment]
So is the solution to just go through and make a bunch of our memoryviews `const`? It looks like that is the expected solution, it's unfortunate if that's the best that can be done but this seems to be an implementation problem with memoryviews themselves so we can live with it now that we put in the time to switch from the older array syntax to memoryviews.

**Comment by bdice** [comment]
@vyasr Yup, that's the solution - just add `const` in front of most memoryviews (except ones that are outputs). I am happy to do this since I am familiar with all the memoryview code.
