### ISSUE TITLE
TrajectoryXML dynamic not working

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#4]
**[Original report](https://bitbucket.org/glotzer/freud/issue/4) by Eric Harper (Bitbucket: [harperic](https://bitbucket.org/harperic), GitHub: [harperic](https://github.com/harperic)).**

----------------------------------------

I believe this needs updating for python 3. It appears that this is an issue with iterating through a dict and updating it at the same time...

Unit test creates following error:

======================================================================
ERROR: test_multiple_file_dynamic (test_trajectory_TrajectoryXML.TestTrajectoryXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/harperic/code/freud/test/test_trajectory_TrajectoryXML.py", line 60, in test_multiple_file_dynamic
    frame = traj[1]
  File "/Users/harperic/local/lib/python/freud/trajectory.py", line 132, in __getitem__
    return self._get_current_frame();
  File "/Users/harperic/local/lib/python/freud/trajectory.py", line 377, in _get_current_frame
    for prop in self.dynamic_props.keys():
RuntimeError: dictionary changed size during iteration

**Comment by bdice** [comment]
**Original comment by Eric Harper (Bitbucket: [harperic](https://bitbucket.org/harperic), GitHub: [harperic](https://github.com/harperic)).**

----------------------------------------

Fixed. Needed to create the library entries before changing them...

**Comment by bdice** [comment]
**Original comment by Eric Harper (Bitbucket: [harperic](https://bitbucket.org/harperic), GitHub: [harperic](https://github.com/harperic)).**

----------------------------------------

Fixed. See last comment.
