### ISSUE TITLE
OVITO support broken by changes in _convert_array

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#766]
**Describe the bug**
I cannot convert an OVITO DataCollection to a freud system-like object. This worked with freud v2.5.1 and I believe it was broken in 8a811d7cc4d8465f81567f01b81a614611250949 or some other piece of #674. @vyasr @Charlottez112

My best guess is that the native dtype of the OVITO Property is `float64` and freud is requiring `float32` but this requirement cannot be met by the read-only array view provided by OVITO's `PropertyView`. While `PropertyView` is seemingly "array-like", it can't be used by `np.require` in the same way as the result of `np.asarray` (view? copy?) that was previously passed in.

**To Reproduce**
1. Install the latest freud (from source) into an OVITO Python environment
2. Open a trajectory in OVITO
3. Use the following viewport modifier:
 
```python
import freud

def render(args):
    pipeline = args.scene.selected_pipeline
    if not pipeline:
        return
    data = pipeline.compute(args.frame)
    system = freud.AABBQuery.from_system(data)
    print(system)
```

**Error output**
```python
The Python script has exited with an error.
Traceback (most recent call last):
  File "<string>", line 12, in render
  File "locality.pyx", line 371, in freud.locality.NeighborQuery.from_system
  File "locality.pyx", line 836, in freud.locality.AABBQuery.__cinit__
  File "util.pyx", line 227, in freud.util._convert_array
  File "/home/bdice/miniconda3/envs/dice/lib/python3.8/site-packages/numpy/core/_asarray.py", line 400, in require
    arr = array(a, dtype=dtype, order=order, copy=False, subok=subok)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.8/site-packages/ovito/data/stdobj/property.py", line 77, in _Property__array__
    return PropertyView(self.__array__impl__(dtype), self)
RuntimeError: Property: Cannot create NumPy array view with dtype other than the native data type of the property.
```

**System configuration (please complete the following information):**
 - OS: Windows / Linux
 - Version of Python: 3.8
 - Version of freud: c68dbce048d77bf5497fbf1066e68088f87497d9

**Comment by bdice** [comment]
https://github.com/glotzerlab/freud/pull/674/files#r605909022

> Could you explain why we don't want `array = np.asarray(array)` here? Is this for reducing the number of copies? I guess this is what's causing the errors

> It's redundant. `np.require` internally has to convert `array` to a numpy array anyway. The problems is that I didn't change enough of the code below, which is still using `array` instead of `return_arr`.

@vyasr It seems like this call to `np.asarray` wasn't redundant, after all. I am going to create a PR that adds back that line. Hopefully it won't negatively impact the attempts to avoid data copies.
